name: flutter_vibrate
description: A Haptic Feedback plugin.
version: 2.0.0
maintainer: Rody Davis (@rodydavis)
homepage: https://github.com/rodydavis/plugins
repository: https://github.com/rodydavis/flutter_vibrate

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=2.0.0'

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: flutter.plugins.vibrate
        pluginClass: VibratePlugin
      ios:
        pluginClass: VibratePlugin